"""Narrow framework-independent persistence ports."""

from types import TracebackType
from typing import Protocol, Self

from security_triage_agent.application.persistence import (
    ActionExecutionRecord,
    AuditEvent,
    PersistedAction,
    TriageExecutionRecord,
)
from security_triage_agent.application.tool_gateway import ToolInvocationRecord
from security_triage_agent.domain.actions import ActionProposal
from security_triage_agent.domain.alerts import SecurityAlert
from security_triage_agent.domain.approvals import ApprovalRecord
from security_triage_agent.domain.triage import TriageResult
from security_triage_agent.evaluation.persistence import EvaluationCaseRecord, EvaluationRunRecord


class AlertRepository(Protocol):
    def add(self, alert: SecurityAlert) -> None: ...
    def get(self, alert_id: str) -> SecurityAlert | None: ...
    def list_recent(self, limit: int = 100) -> tuple[SecurityAlert, ...]: ...


class ExecutionRepository(Protocol):
    def add(self, execution: TriageExecutionRecord) -> None: ...
    def get(self, execution_id: str) -> TriageExecutionRecord | None: ...
    def get_by_idempotency_key(self, key: str) -> TriageExecutionRecord | None: ...
    def replace(self, execution: TriageExecutionRecord) -> None: ...
    def list_for_alert(self, alert_id: str) -> tuple[TriageExecutionRecord, ...]: ...


class ToolInvocationRepository(Protocol):
    def add(
        self, invocation: ToolInvocationRecord, result: dict[str, object] | None = None
    ) -> None: ...
    def list_for_execution(self, execution_id: str) -> tuple[ToolInvocationRecord, ...]: ...


class TriageResultRepository(Protocol):
    def add(self, result_id: str, execution_id: str, result: TriageResult) -> None: ...
    def get_for_execution(self, execution_id: str) -> TriageResult | None: ...


class ActionRepository(Protocol):
    def add(
        self, execution_id: str, action: ActionProposal, policy_version: str = "1.0.0"
    ) -> None: ...
    def get(self, action_id: str) -> ActionProposal | None: ...
    def get_persisted(self, action_id: str) -> PersistedAction | None: ...


class ApprovalRepository(Protocol):
    def add(self, approval: ApprovalRecord) -> None: ...
    def get(self, approval_id: str) -> ApprovalRecord | None: ...
    def get_for_action(self, action_id: str) -> ApprovalRecord | None: ...


class ActionExecutionRepository(Protocol):
    def add(self, execution: ActionExecutionRecord) -> None: ...
    def get(self, action_execution_id: str) -> ActionExecutionRecord | None: ...
    def get_for_action(self, action_id: str) -> ActionExecutionRecord | None: ...
    def replace(self, execution: ActionExecutionRecord) -> None: ...


class AuditRepository(Protocol):
    def append(self, event: AuditEvent) -> None: ...
    def list_for_target(self, target_type: str, target_id: str) -> tuple[AuditEvent, ...]: ...


class EvaluationRepository(Protocol):
    def add_run(self, run: EvaluationRunRecord) -> None: ...
    def add_case(self, case: EvaluationCaseRecord) -> None: ...
    def get_run(self, run_id: str) -> EvaluationRunRecord | None: ...
    def list_cases(self, run_id: str) -> tuple[EvaluationCaseRecord, ...]: ...


class UnitOfWork(Protocol):
    alerts: AlertRepository
    executions: ExecutionRepository
    tool_invocations: ToolInvocationRepository
    triage_results: TriageResultRepository
    actions: ActionRepository
    approvals: ApprovalRepository
    action_executions: ActionExecutionRepository
    audit: AuditRepository
    evaluations: EvaluationRepository

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def flush(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
